# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

# Velocity Controllers ---------------------------------------
steer_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: steer_wheel_joint
  pid: {p: 5.0, i: 0.0, d: 0.0}
  
# Velocity Controllers ---------------------------------------
steer_direction_controller:
  type: position_controllers/JointPositionController
  joint: disk_link_joint
  pid: {p: 10.0, i: 0.01, d: 1.0}
