<?xml version="1.0"?>
<robot name="slider" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- define constants -->
<xacro:property name="PI" value="3.1415926" />
<xacro:property name="mass" value="1" /> <!-- kg -->
<xacro:property name="width" value="0.1" /> <!-- 0.1m -->
<xacro:property name="height1" value="2" /> <!-- 2m -->
<xacro:property name="height2" value="1" /> <!-- 1m -->

<!-- define links -->
<link name="world" />

<!-- Base Link-->
<link name="base_link">
  <collision>
    <geometry>
      <box size="${width} ${width} ${height1}" />
    </geometry>
    <origin xyz="0 0 ${height1/2}" rpy="0 0 0" />
  </collision>
  
  <visual>
    <geometry>
      <box size="${width} ${width} ${height1}" />
    </geometry>
    <origin xyz="0 0 ${height1/2}" rpy="0 0 0" />
  </visual>
  
  <inertial>
    <mass value="${mass}" />
    <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
  </inertial>
</link>

<gazebo reference="base_link">
  <material>Gazebo/Orange</material>
</gazebo>

<joint name="ground_joint" type="fixed">  <!-- fix to the ground -->
  <parent link="world" />
  <child link="base_link" />
</joint>

<!-- Link 2 -->
<link name="link2">
  <collision>
    <geometry>
      <box size="${width} ${width} ${height2}" />
    </geometry>
    <origin xyz="0 0 ${height2/2}" rpy="0 0 0" />
  </collision>
  
  <visual>
    <geometry>
      <box size="${width} ${width} ${height2}" />
    </geometry>
    <origin xyz="0 0 ${height2/2}" rpy="0 0 0" />
  </visual>
  
  <inertial>
    <mass value="${mass/2}" />
    <inertia
	  ixx="${mass / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height2*height2 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
  </inertial>
</link>

<gazebo reference="link2">
  <material>Gazebo/Black</material>
</gazebo>

<joint name="joint1" type="prismatic"> 
  <parent link="base_link" />
  <child link="link2" />
  <limit effort="100" velocity="0.2" lower="-1.0" upper="1.0" />
  <origin xyz="0 ${width} ${height1/2}" rpy="0 0 0" />
  <axis xyz="0 0 1" />
</joint>


<transmission name="tran1">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="joint1">
    <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
  </joint>
  <actuator name="motor1">
    <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>

<!-- ros_control plugin -->
 <gazebo>
   <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
     <robotNamespace>/slider</robotNamespace>
     <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
     <legacyModeNS>true</legacyModeNS>  <!-- KC_DBG : to avoid gazebo version warring-->
   </plugin>
 </gazebo>
 
</robot>